import { User, Examination, Question, ExaminationSession, AuditLog } from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-admin-01',
    fullName: 'Dr. Okon E. Bassey',
    email: 'hod.gns@fedpolyukana.edu.ng',
    role: 'admin',
    department: 'Directorate of General Studies',
    level: 'Chief Lecturer / HOD',
    school: 'School of General Studies',
    workstation: 'Admin Terminal GNS-01',
    status: true,
    createdAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'usr-lecturer-01',
    fullName: 'Mrs. Aniefiok U. Akpan',
    email: 'a.akpan@fedpolyukana.edu.ng',
    role: 'lecturer',
    department: 'Directorate of General Studies (English Unit)',
    level: 'Principal Lecturer',
    school: 'School of General Studies',
    workstation: 'Examiner Terminal 02',
    status: true,
    createdAt: '2026-01-15T09:30:00Z',
  },
  {
    id: 'usr-lecturer-02',
    fullName: 'Mr. Emmanuel T. Udosen',
    email: 'e.udosen@fedpolyukana.edu.ng',
    role: 'lecturer',
    department: 'Directorate of General Studies (Citizenship Unit)',
    level: 'Senior Lecturer',
    school: 'School of General Studies',
    workstation: 'Examiner Terminal 03',
    status: true,
    createdAt: '2026-01-20T10:00:00Z',
  },
  {
    id: 'usr-student-01',
    fullName: 'John Sunday Udoh',
    email: 'john.udoh@student.fedpolyukana.edu.ng',
    studentId: '2025/ND/SLT/014',
    role: 'student',
    department: 'Science Laboratory Technology',
    level: 'ND I',
    school: 'School of Applied Sciences',
    workstation: 'CBT LAB 1 · PC-14',
    status: true,
    createdAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'usr-student-02',
    fullName: 'Mary Anietie Ekpo',
    email: 'mary.ekpo@student.fedpolyukana.edu.ng',
    studentId: '2025/ND/CS/042',
    role: 'student',
    department: 'Computer Science',
    level: 'ND I',
    school: 'School of Applied Sciences',
    workstation: 'CBT LAB 1 · PC-15',
    status: true,
    createdAt: '2026-02-01T10:15:00Z',
  },
  {
    id: 'usr-student-03',
    fullName: 'Peter Nsikak Inyang',
    email: 'peter.inyang@student.fedpolyukana.edu.ng',
    studentId: '2025/ND/EEE/029',
    role: 'student',
    department: 'Electrical Electronics Engineering',
    level: 'ND I',
    school: 'School of Engineering',
    workstation: 'CBT LAB 1 · PC-16',
    status: true,
    createdAt: '2026-02-01T10:30:00Z',
  },
  {
    id: 'usr-student-04',
    fullName: 'Grace Idorenyin Etim',
    email: 'grace.etim@student.fedpolyukana.edu.ng',
    studentId: '2025/ND/STA/008',
    role: 'student',
    department: 'Statistics',
    level: 'ND I',
    school: 'School of Applied Sciences',
    workstation: 'CBT LAB 1 · PC-17',
    status: true,
    createdAt: '2026-02-02T11:00:00Z',
  },
  {
    id: 'usr-student-05',
    fullName: 'Emmanuel Bassey Udo',
    email: 'emmanuel.udo@student.fedpolyukana.edu.ng',
    studentId: '2025/ND/CE/051',
    role: 'student',
    department: 'Civil Engineering',
    level: 'ND I',
    school: 'School of Engineering',
    workstation: 'CBT LAB 1 · PC-18',
    status: true,
    createdAt: '2026-02-02T11:30:00Z',
  },
];

export const INITIAL_EXAMINATIONS: Examination[] = [
  {
    id: 'exam-gns-101',
    title: 'Use of English I',
    courseCode: 'GNS 101',
    courseCategory: 'english',
    creditUnits: 2,
    semester: 'First Semester',
    academicSession: '2025/2026',
    department: 'Directorate of General Studies',
    durationMinutes: 45,
    totalMarks: 50,
    passThresholdPercentage: 50,
    startTime: '2026-09-25T08:00:00Z',
    endTime: '2026-10-30T18:00:00Z',
    status: 'active',
    createdBy: 'Mrs. Aniefiok U. Akpan',
    createdAt: '2026-09-20T10:00:00Z',
    instructions: '1. Read each question carefully before selecting an answer.\n2. You are allowed 45 minutes for this examination.\n3. Each question carries equal marks (5 points each).\n4. Student responses are automatically saved in real time to the server.\n5. Click "Submit Examination" once you have concluded all questions.',
    releaseResultsImmediately: true,
    shuffleQuestions: true,
    shuffleOptions: true,
    allowReview: true,
  },
  {
    id: 'exam-gns-102',
    title: 'Citizenship Education I',
    courseCode: 'GNS 102',
    courseCategory: 'citizenship',
    creditUnits: 2,
    semester: 'Second Semester',
    academicSession: '2025/2026',
    department: 'Directorate of General Studies',
    durationMinutes: 30,
    totalMarks: 50,
    passThresholdPercentage: 50,
    startTime: '2026-09-28T09:00:00Z',
    endTime: '2026-10-31T17:00:00Z',
    status: 'active',
    createdBy: 'Mr. Emmanuel T. Udosen',
    createdAt: '2026-09-21T11:00:00Z',
    instructions: '1. This test assesses knowledge of the Nigerian Constitution, organs of government, and fundamental human rights.\n2. Choose the single most appropriate option for each question.\n3. The allocated duration is 30 minutes.\n4. When the countdown reaches 00:00, the examination will automatically submit.',
    releaseResultsImmediately: true,
    shuffleQuestions: true,
    shuffleOptions: true,
    allowReview: true,
  },
  {
    id: 'exam-gns-201',
    title: 'Use of English II & Communication Skills',
    courseCode: 'GNS 201',
    courseCategory: 'english',
    creditUnits: 2,
    semester: 'First Semester',
    academicSession: '2025/2026',
    department: 'Directorate of General Studies',
    durationMinutes: 40,
    totalMarks: 50,
    passThresholdPercentage: 50,
    startTime: '2026-10-05T08:00:00Z',
    endTime: '2026-11-10T18:00:00Z',
    status: 'upcoming',
    createdBy: 'Mrs. Aniefiok U. Akpan',
    createdAt: '2026-09-22T09:00:00Z',
    instructions: '1. Covers technical report writing, official correspondence, and meeting documentation.\n2. Ensure all questions are attempted before submission.',
    releaseResultsImmediately: false,
    shuffleQuestions: true,
    shuffleOptions: true,
    allowReview: true,
  },
  {
    id: 'exam-gns-202',
    title: 'Citizenship Education II & Peace Studies',
    courseCode: 'GNS 202',
    courseCategory: 'citizenship',
    creditUnits: 2,
    semester: 'Second Semester',
    academicSession: '2025/2026',
    department: 'Directorate of General Studies',
    durationMinutes: 35,
    totalMarks: 50,
    passThresholdPercentage: 50,
    startTime: '2026-10-12T08:00:00Z',
    endTime: '2026-11-15T18:00:00Z',
    status: 'upcoming',
    createdBy: 'Mr. Emmanuel T. Udosen',
    createdAt: '2026-09-22T10:00:00Z',
    instructions: '1. Focuses on peace, conflict resolution, democratic ethics, and national integration in Nigeria.',
    releaseResultsImmediately: true,
    shuffleQuestions: true,
    shuffleOptions: false,
    allowReview: true,
  },
  {
    id: 'exam-gns-111',
    title: 'Communication in English I',
    courseCode: 'GNS 111',
    courseCategory: 'communication',
    creditUnits: 2,
    semester: 'First Semester',
    academicSession: '2025/2026',
    department: 'Directorate of General Studies',
    durationMinutes: 30,
    totalMarks: 40,
    passThresholdPercentage: 50,
    startTime: '2026-09-20T08:00:00Z',
    endTime: '2026-10-25T18:00:00Z',
    status: 'active',
    createdBy: 'Dr. Okon E. Bassey',
    createdAt: '2026-09-18T14:00:00Z',
    instructions: '1. Evaluates oral communication, phonetic transcription, and study skills.',
    releaseResultsImmediately: true,
    shuffleQuestions: true,
    shuffleOptions: true,
    allowReview: true,
  },
  {
    id: 'exam-eed-126',
    title: 'Introduction to Entrepreneurship Development',
    courseCode: 'EED 126',
    courseCategory: 'entrepreneurship',
    creditUnits: 2,
    semester: 'Second Semester',
    academicSession: '2025/2026',
    department: 'Directorate of General Studies',
    durationMinutes: 45,
    totalMarks: 50,
    passThresholdPercentage: 50,
    startTime: '2026-10-15T09:00:00Z',
    endTime: '2026-11-20T17:00:00Z',
    status: 'upcoming',
    createdBy: 'Dr. Okon E. Bassey',
    createdAt: '2026-09-24T12:00:00Z',
    instructions: '1. National Board for Technical Education (NBTE) standard syllabus for Entrepreneurship Education.',
    releaseResultsImmediately: true,
    shuffleQuestions: true,
    shuffleOptions: true,
    allowReview: true,
  },
];

export const INITIAL_QUESTIONS: Question[] = [
  // ==========================================
  // GNS 101: USE OF ENGLISH I (10 Questions)
  // ==========================================
  {
    id: 'q-gns101-01',
    examinationId: 'exam-gns-101',
    questionText: 'Which of the following parts of speech is used to express sudden or strong spontaneous emotion?',
    optionA: 'Conjunction',
    optionB: 'Interjection',
    optionC: 'Preposition',
    optionD: 'Adverb',
    correctOption: 'B',
    marks: 5,
    questionOrder: 1,
    topic: 'Parts of Speech',
    explanation: 'An interjection expresses spontaneous emotional states (e.g., Ah!, Bravo!, Alas!, Oh!).'
  },
  {
    id: 'q-gns101-02',
    examinationId: 'exam-gns-101',
    questionText: 'Identify the sentence with correct grammatical concord:',
    optionA: 'Neither of the polytechnic students were present yesterday.',
    optionB: 'Neither of the polytechnic students was present yesterday.',
    optionC: 'Neither of the polytechnic students are present yesterday.',
    optionD: 'Neither of the polytechnic students have been present yesterday.',
    correctOption: 'B',
    marks: 5,
    questionOrder: 2,
    topic: 'Subject-Verb Agreement',
    explanation: 'The distributive pronoun "neither" is grammatically singular and takes the singular past verb "was".'
  },
  {
    id: 'q-gns101-03',
    examinationId: 'exam-gns-101',
    questionText: 'In English phonetics, how many pure vowel sounds (monophthongs) exist in Standard Received Pronunciation?',
    optionA: '8',
    optionB: '12',
    optionC: '20',
    optionD: '24',
    correctOption: 'B',
    marks: 5,
    questionOrder: 3,
    topic: 'Phonetics & Phonology',
    explanation: 'There are 12 monophthongs (pure vowels) and 8 diphthongs, giving 20 vowel sounds in total.'
  },
  {
    id: 'q-gns101-04',
    examinationId: 'exam-gns-101',
    questionText: 'A sentence that contains one independent clause and at least one dependent (subordinate) clause is a:',
    optionA: 'Simple sentence',
    optionB: 'Compound sentence',
    optionC: 'Complex sentence',
    optionD: 'Compound-complex sentence',
    correctOption: 'C',
    marks: 5,
    questionOrder: 4,
    topic: 'Sentence Types',
    explanation: 'A complex sentence combines one main independent clause with one or more subordinate clauses.'
  },
  {
    id: 'q-gns101-05',
    examinationId: 'exam-gns-101',
    questionText: 'Choose the word that is NEAREST in meaning (synonym) to the word "Meticulous":',
    optionA: 'Careless and superficial',
    optionB: 'Painstaking, thorough and precise',
    optionC: 'Overly hasty',
    optionD: 'Completely indifferent',
    correctOption: 'B',
    marks: 5,
    questionOrder: 5,
    topic: 'Lexis & Structure',
    explanation: 'Meticulous refers to showing immense attention to detail and thorough accuracy.'
  },
  {
    id: 'q-gns101-06',
    examinationId: 'exam-gns-101',
    questionText: 'Which punctuation mark is correctly used to connect two closely related independent clauses without a coordinating conjunction?',
    optionA: 'Comma',
    optionB: 'Semicolon',
    optionC: 'Hyphen',
    optionD: 'Apostrophe',
    correctOption: 'B',
    marks: 5,
    questionOrder: 6,
    topic: 'Mechanics & Punctuation',
    explanation: 'A semicolon links two grammatically complete thoughts that are closely connected in meaning.'
  },
  {
    id: 'q-gns101-07',
    examinationId: 'exam-gns-101',
    questionText: 'Select the correct passive voice construction for: "The examination invigilator distributed the question scripts."',
    optionA: 'The question scripts are distributed by the examination invigilator.',
    optionB: 'The question scripts were distributed by the examination invigilator.',
    optionC: 'The question scripts had been distributed by the examination invigilator.',
    optionD: 'The question scripts was distributed by the examination invigilator.',
    correctOption: 'B',
    marks: 5,
    questionOrder: 7,
    topic: 'Active & Passive Voice',
    explanation: 'The past tense "distributed" becomes plural past passive "were distributed" with plural subject scripts.'
  },
  {
    id: 'q-gns101-08',
    examinationId: 'exam-gns-101',
    questionText: 'In academic writing, what is the primary role of a topic sentence in an expository paragraph?',
    optionA: 'To deliver the final bibliography reference',
    optionB: 'To provide statistical graphs and figures',
    optionC: 'To state and focus the central controlling idea of that paragraph',
    optionD: 'To introduce the author biographical sketch',
    correctOption: 'C',
    marks: 5,
    questionOrder: 8,
    topic: 'Paragraph Development',
    explanation: 'The topic sentence states the paragraph main idea, supported by subsequent sentences.'
  },
  {
    id: 'q-gns101-09',
    examinationId: 'exam-gns-101',
    questionText: 'Choose the option that represents the correctly spelt word:',
    optionA: 'Accomodation',
    optionB: 'Accommodation',
    optionC: 'Acommodation',
    optionD: 'Acomodation',
    correctOption: 'B',
    marks: 5,
    questionOrder: 9,
    topic: 'Spelling Rules',
    explanation: 'Accommodation is spelt with double "c" and double "m".'
  },
  {
    id: 'q-gns101-10',
    examinationId: 'exam-gns-101',
    questionText: 'When two singular nouns are joined by "and" but refer to a single entity, office, or concept, the verb must be:',
    optionA: 'Plural',
    optionB: 'Singular',
    optionC: 'Passive infinitive',
    optionD: 'Pluperfect subjunctive',
    correctOption: 'B',
    marks: 5,
    questionOrder: 10,
    topic: 'Concord of Proximity',
    explanation: 'Example: "Bread and butter is his favorite breakfast" or "The Chairman and Chief Executive has arrived".'
  },

  // ===============================================
  // GNS 102: CITIZENSHIP EDUCATION I (10 Questions)
  // ===============================================
  {
    id: 'q-gns102-01',
    examinationId: 'exam-gns-102',
    questionText: 'Under the 1999 Constitution of the Federal Republic of Nigeria (as amended), which arm of government is empowered to interpret laws and adjudicate disputes?',
    optionA: 'The Executive',
    optionB: 'The Legislature',
    optionC: 'The Judiciary',
    optionD: 'The Civil Service Commission',
    correctOption: 'C',
    marks: 5,
    questionOrder: 1,
    topic: 'Arms of Government',
    explanation: 'The Judiciary, headed by the Chief Justice of Nigeria, exercises judicial powers and interprets constitutional provisions.'
  },
  {
    id: 'q-gns102-02',
    examinationId: 'exam-gns-102',
    questionText: 'How many geopolitical zones are recognized in the political structure of the Federal Republic of Nigeria?',
    optionA: '4',
    optionB: '6',
    optionC: '12',
    optionD: '36',
    correctOption: 'B',
    marks: 5,
    questionOrder: 2,
    topic: 'Nigerian Geopolitical Structure',
    explanation: 'Nigeria is divided into six geopolitical zones: South-South, South-East, South-West, North-Central, North-East, and North-West.'
  },
  {
    id: 'q-gns102-03',
    examinationId: 'exam-gns-102',
    questionText: 'Fundamental Human Rights in Nigeria are formally codified in which chapter of the 1999 Constitution?',
    optionA: 'Chapter I',
    optionB: 'Chapter II',
    optionC: 'Chapter IV',
    optionD: 'Chapter VI',
    correctOption: 'C',
    marks: 5,
    questionOrder: 3,
    topic: 'Constitutional Rights',
    explanation: 'Chapter IV covers rights including the Right to Life, Dignity of Human Person, Personal Liberty, and Fair Hearing.'
  },
  {
    id: 'q-gns102-04',
    examinationId: 'exam-gns-102',
    questionText: 'The constitutional doctrine of Federalism fundamentally implies:',
    optionA: 'The absolute vesting of all authority in a unitary national president',
    optionB: 'The formal division of powers between a central government and component constituent units (states)',
    optionC: 'Governance conducted exclusively through customary rulers',
    optionD: 'A system where municipal local governments are sovereign over the federation',
    correctOption: 'B',
    marks: 5,
    questionOrder: 4,
    topic: 'Federalism',
    explanation: 'Federalism divides governmental authority between federal, state, and local governments with defined legislative lists.'
  },
  {
    id: 'q-gns102-05',
    examinationId: 'exam-gns-102',
    questionText: 'A citizen who acquires Nigerian citizenship by being born to Nigerian parents has acquired citizenship by:',
    optionA: 'Naturalization',
    optionB: 'Registration',
    optionC: 'Birth',
    optionD: 'Conquest',
    correctOption: 'C',
    marks: 5,
    questionOrder: 5,
    topic: 'Citizenship Acquisition',
    explanation: 'Section 25 of the 1999 Constitution establishes citizenship by birth for individuals born in or outside Nigeria to Nigerian parent(s).'
  },
  {
    id: 'q-gns102-06',
    examinationId: 'exam-gns-102',
    questionText: 'Which statutory body is constitutionally vested with the responsibility of conducting federal and state general elections in Nigeria?',
    optionA: 'National Orientation Agency (NOA)',
    optionB: 'Independent National Electoral Commission (INEC)',
    optionC: 'Public Complaints Commission (PCC)',
    optionD: 'National Judicial Council (NJC)',
    correctOption: 'B',
    marks: 5,
    questionOrder: 6,
    topic: 'Democratic Institutions',
    explanation: 'INEC is established under Section 153 of the 1999 Constitution to organize and supervise elections.'
  },
  {
    id: 'q-gns102-07',
    examinationId: 'exam-gns-102',
    questionText: 'The legal principle of the "Rule of Law" as expounded by A.V. Dicey includes all of the following EXCEPT:',
    optionA: 'Supremacy of regular law over arbitrary power',
    optionB: 'Equality before the law for all citizens',
    optionC: 'Absolute immunity for state officials against criminal prosecution',
    optionD: 'Protection of individual rights by the judiciary',
    correctOption: 'C',
    marks: 5,
    questionOrder: 7,
    topic: 'Rule of Law',
    explanation: 'The Rule of Law prohibits arbitrary executive power and insists that no person is above the law.'
  },
  {
    id: 'q-gns102-08',
    examinationId: 'exam-gns-102',
    questionText: 'Which of the following is a designated civic duty of a responsible Nigerian citizen?',
    optionA: 'Evasion of municipal assessment taxes',
    optionB: 'Payment of legitimate taxes and respect for national symbols',
    optionC: 'Disregard for environmental sanitation laws',
    optionD: 'Refusal to participate in national voter registration',
    correctOption: 'B',
    marks: 5,
    questionOrder: 8,
    topic: 'Duties of a Citizen',
    explanation: 'Section 24 of the Constitution mandates citizens to abide by the Constitution, pay taxes, and defend the nation.'
  },
  {
    id: 'q-gns102-09',
    examinationId: 'exam-gns-102',
    questionText: 'The legislative arm of the Federal Government of Nigeria is bicameral, consisting of:',
    optionA: 'The Senate and the House of Representatives',
    optionB: 'The Supreme Court and the Court of Appeal',
    optionC: 'The Federal Executive Council and Council of State',
    optionD: 'The National Assembly and the State Assembly',
    correctOption: 'A',
    marks: 5,
    questionOrder: 9,
    topic: 'Legislative Arm',
    explanation: 'The National Assembly consists of 109 Senators and 360 House of Representatives members.'
  },
  {
    id: 'q-gns102-10',
    examinationId: 'exam-gns-102',
    questionText: 'The Motto of the Federal Republic of Nigeria as emblazoned on the Coat of Arms is:',
    optionA: 'Peace, Order and Good Governance',
    optionB: 'Unity and Faith, Peace and Progress',
    optionC: 'Forward Ever, Backward Never',
    optionD: 'Liberty, Equality and Fraternity',
    correctOption: 'B',
    marks: 5,
    questionOrder: 10,
    topic: 'National Identity & Symbols',
    explanation: 'The official national motto of Nigeria is "Unity and Faith, Peace and Progress".'
  },

  // ========================================================
  // GNS 111: COMMUNICATION IN ENGLISH I (8 Questions)
  // ========================================================
  {
    id: 'q-gns111-01',
    examinationId: 'exam-gns-111',
    questionText: 'Which phase of the human communication process involves translating conceived thoughts into verbal or non-verbal symbols?',
    optionA: 'Decoding',
    optionB: 'Encoding',
    optionC: 'Feedback loop',
    optionD: 'Attenuation',
    correctOption: 'B',
    marks: 5,
    questionOrder: 1,
    topic: 'Communication Theory',
    explanation: 'Encoding is the formulation of thoughts and intentions into a transmittable code or language.'
  },
  {
    id: 'q-gns111-02',
    examinationId: 'exam-gns-111',
    questionText: 'In oral communication, "intonation" refers to:',
    optionA: 'The volume at which consonants are pronounced',
    optionB: 'The rise and fall of the pitch of the voice in connected speech',
    optionC: 'The dictionary definition of a polysemic noun',
    optionD: 'The rate of handwriting on an examination script',
    correctOption: 'B',
    marks: 5,
    questionOrder: 2,
    topic: 'Suprasegmentals',
    explanation: 'Intonation is the modulation of vocal pitch across phrases and sentences.'
  },
  {
    id: 'q-gns111-03',
    examinationId: 'exam-gns-111',
    questionText: 'Which organ is considered the primary articulator involved in the production of dental sounds such as /θ/ and /ð/?',
    optionA: 'Uvula and nasal cavity',
    optionB: 'Tongue tip against the upper teeth',
    optionC: 'Lower lip against upper incisors',
    optionD: 'Glottis alone',
    correctOption: 'B',
    marks: 5,
    questionOrder: 3,
    topic: 'Phonetics & Articulatory Organs',
    explanation: 'The tongue tip placed behind or between the teeth produces the dental fricatives in "thin" and "this".'
  },
  {
    id: 'q-gns111-04',
    examinationId: 'exam-gns-111',
    questionText: 'What type of reading technique is most effective when searching for a specific date or name in a lengthy text?',
    optionA: 'Extensive browsing',
    optionB: 'Scanning',
    optionC: 'Skimming',
    optionD: 'Proofreading',
    correctOption: 'B',
    marks: 5,
    questionOrder: 4,
    topic: 'Reading Skills',
    explanation: 'Scanning involves rapidly moving eyes across text to locate a targeted piece of information.'
  },
];

export const INITIAL_SESSIONS: ExaminationSession[] = [
  {
    id: 'sess-001',
    examinationId: 'exam-gns-101',
    studentId: 'usr-student-02',
    studentName: 'Mary Anietie Ekpo',
    studentRegNo: '2025/ND/CS/042',
    department: 'Computer Science',
    startedAt: '2026-09-26T10:00:00Z',
    submittedAt: '2026-09-26T10:38:00Z',
    status: 'submitted',
    score: 45,
    percentage: 90,
    timeSpentSeconds: 2280,
    answers: {
      'q-gns101-01': 'B',
      'q-gns101-02': 'B',
      'q-gns101-03': 'B',
      'q-gns101-04': 'C',
      'q-gns101-05': 'B',
      'q-gns101-06': 'B',
      'q-gns101-07': 'B',
      'q-gns101-08': 'C',
      'q-gns101-09': 'B',
      'q-gns101-10': 'A',
    },
    flaggedQuestionIds: [],
    tabSwitchCount: 0,
    questionOrder: ['q-gns101-01', 'q-gns101-02', 'q-gns101-03', 'q-gns101-04', 'q-gns101-05', 'q-gns101-06', 'q-gns101-07', 'q-gns101-08', 'q-gns101-09', 'q-gns101-10'],
    optionOrders: {},
    lastSavedAt: '2026-09-26T10:38:00Z',
  },
  {
    id: 'sess-002',
    examinationId: 'exam-gns-101',
    studentId: 'usr-student-03',
    studentName: 'Peter Nsikak Inyang',
    studentRegNo: '2025/ND/EEE/029',
    department: 'Electrical Electronics Engineering',
    startedAt: '2026-09-26T11:10:00Z',
    submittedAt: '2026-09-26T11:42:00Z',
    status: 'submitted',
    score: 35,
    percentage: 70,
    timeSpentSeconds: 1920,
    answers: {
      'q-gns101-01': 'B',
      'q-gns101-02': 'A',
      'q-gns101-03': 'B',
      'q-gns101-04': 'C',
      'q-gns101-05': 'B',
      'q-gns101-06': 'A',
      'q-gns101-07': 'B',
      'q-gns101-08': 'C',
      'q-gns101-09': 'A',
      'q-gns101-10': 'B',
    },
    flaggedQuestionIds: [],
    tabSwitchCount: 1,
    questionOrder: ['q-gns101-01', 'q-gns101-02', 'q-gns101-03', 'q-gns101-04', 'q-gns101-05', 'q-gns101-06', 'q-gns101-07', 'q-gns101-08', 'q-gns101-09', 'q-gns101-10'],
    optionOrders: {},
    lastSavedAt: '2026-09-26T11:42:00Z',
  },
  {
    id: 'sess-003',
    examinationId: 'exam-gns-102',
    studentId: 'usr-student-04',
    studentName: 'Grace Idorenyin Etim',
    studentRegNo: '2025/ND/STA/008',
    department: 'Statistics',
    startedAt: '2026-09-27T09:00:00Z',
    submittedAt: '2026-09-27T09:28:00Z',
    status: 'submitted',
    score: 40,
    percentage: 80,
    timeSpentSeconds: 1680,
    answers: {
      'q-gns102-01': 'C',
      'q-gns102-02': 'B',
      'q-gns102-03': 'C',
      'q-gns102-04': 'B',
      'q-gns102-05': 'C',
      'q-gns102-06': 'B',
      'q-gns102-07': 'C',
      'q-gns102-08': 'B',
      'q-gns102-09': 'A',
      'q-gns102-10': 'A',
    },
    flaggedQuestionIds: [],
    tabSwitchCount: 0,
    questionOrder: ['q-gns102-01', 'q-gns102-02', 'q-gns102-03', 'q-gns102-04', 'q-gns102-05', 'q-gns102-06', 'q-gns102-07', 'q-gns102-08', 'q-gns102-09', 'q-gns102-10'],
    optionOrders: {},
    lastSavedAt: '2026-09-27T09:28:00Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-101',
    userId: 'usr-admin-01',
    userName: 'Dr. Okon E. Bassey',
    userRole: 'admin',
    action: 'CREATE_EXAMINATION',
    description: 'Configured GNS 101: Use of English I for 2025/2026 First Semester Examination Diet',
    ipAddress: '10.20.1.4',
    timestamp: '2026-09-20T10:00:00Z',
  },
  {
    id: 'log-102',
    userId: 'usr-lecturer-02',
    userName: 'Mr. Emmanuel T. Udosen',
    userRole: 'lecturer',
    action: 'ADD_QUESTIONS',
    description: 'Updated Citizenship Education I (GNS 102) Question Bank validation items',
    ipAddress: '10.20.1.18',
    timestamp: '2026-09-21T11:15:00Z',
  },
  {
    id: 'log-103',
    userId: 'usr-student-02',
    userName: 'Mary Anietie Ekpo',
    userRole: 'student',
    action: 'SUBMIT_EXAM',
    description: 'Submitted GNS 101 Examination (Score: 45/50, 90%, Terminal: CBT LAB 1 · PC-15)',
    ipAddress: '10.20.2.15',
    timestamp: '2026-09-26T10:38:00Z',
  },
  {
    id: 'log-104',
    userId: 'usr-student-03',
    userName: 'Peter Nsikak Inyang',
    userRole: 'student',
    action: 'FOCUS_LOSS',
    description: 'Candidate exited examination window focus (Count: 1, Logged for Chief Proctor Review)',
    ipAddress: '10.20.2.16',
    timestamp: '2026-09-26T11:22:15Z',
  },
];
